import { defineConfig } from "@playwright/test";

// Generated by Dyad. Dyad starts the server for the run itself — an
// isolated run-scoped one when sandboxing is on, otherwise your normal preview
// — so we point baseURL at whichever it selected (passed via env) rather than
// using Playwright's `webServer` (which would double-start the app).
// // Uses your installed Google Chrome (no extra browser download).
export default defineConfig({
  testDir: "./e2e-tests",
  // Run serially against the single dev server.
  workers: 1,
  fullyParallel: false,
  reporter: [["json", { outputFile: "test-results/results.json" }]],
  use: {
    baseURL: process.env.DYAD_TEST_BASE_URL || "http://localhost:32100",
    // Slow motion: Dyad sets DYAD_TEST_SLOW_MO (milliseconds between
    // actions) while the Tests panel's slow-motion toggle is on, so a run is
    // easy to follow. Unset means full speed.
    launchOptions: { slowMo: Number(process.env.DYAD_TEST_SLOW_MO) || 0 },
    channel: "chrome",
    // Off for a preview run: tracing expects browser-global CDP access, which
    // the preview-only automation broker deliberately rejects. The fixture
    // shim attaches a screenshot of the selected page instead.
    screenshot: process.env.DYAD_PREVIEW_CDP_ENDPOINT
      ? "off"
      : "only-on-failure",
    trace: process.env.DYAD_PREVIEW_CDP_ENDPOINT ? "off" : "retain-on-failure",
  },
});
