import { ArrowRight, Check, ClipboardList, Cpu, Eye, FileText, Laptop, Search, ShieldCheck, Wrench } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import { BrandMark, SectionEyebrow } from "@/components/BrandMark";
import { PublicHeader } from "@/components/PublicHeader";
import { serviceCategories } from "@/lib/serviceCatalog";

const processSteps = [
  { number: "01", title: "Submit a Repair Request", text: "Tell us what is happening, share the device details, and send your request through the repair form." },
  { number: "02", title: "Technician Diagnosis", text: "A technician reviews the issue and works through the device carefully to understand what is needed." },
  { number: "03", title: "Receive a Quotation", text: "We share the recommended work and quotation so you can make an informed decision." },
  { number: "04", title: "Approve the Repair", text: "Choose whether to proceed before repair work begins." },
  { number: "05", title: "Repair in Progress", text: "The approved repair moves forward while your request keeps its place in the workflow." },
  { number: "06", title: "Ready for Pickup / Completed", text: "Once the work is complete, you can follow the latest status and arrange the next step." },
];

const customerBenefits = [
  { icon: ClipboardList, title: "Start with the right details", text: "Describe the problem once and include the context that helps the team understand your device." },
  { icon: Eye, title: "Understand what happens next", text: "Follow a clear repair journey from request through diagnosis, quotation, approval, and completion." },
  { icon: ShieldCheck, title: "Stay in control", text: "Review the recommendation and quotation before deciding whether the repair should proceed." },
];

const categoryIcons: LucideIcon[] = [Search, Laptop, Cpu, Wrench, Wrench, FileText, ShieldCheck, Cpu];

export default function About() {
  return (
    <div id="top" className="overflow-hidden bg-[#fbfaf8] text-[#252525]">
      <section className="relative bg-[#f5f4f1]">
        <PublicHeader />
        <div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-36 sm:px-8 sm:pb-24 lg:grid-cols-[1.05fr_0.95fr] lg:px-10 lg:pb-28 lg:pt-44">
          <div className="animate-fade-up">
            <SectionEyebrow>About FixPoint</SectionEyebrow>
            <h1 className="max-w-2xl font-display text-[3.4rem] font-bold leading-[0.96] tracking-[-0.07em] sm:text-6xl lg:text-[5.1rem]">A clearer way to get your device <span className="text-[#B4232C]">fixed.</span></h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-[#66615b] sm:text-lg">FixPoint helps customers move from a repair question to a clear next step. Share what is wrong, understand the recommendation, and keep up with the repair without the guesswork.</p>
            <div className="mt-9 flex flex-wrap gap-3">
              <Link to="/request" className="group inline-flex items-center gap-3 rounded-full bg-[#B4232C] px-6 py-4 text-sm font-bold text-white shadow-[0_14px_28px_rgba(180,35,44,0.2)] transition-transform hover:-translate-y-1">Request a Repair <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></Link>
              <Link to="/track" className="inline-flex items-center gap-2 rounded-full border border-[#d9d5cf] bg-white px-6 py-4 text-sm font-bold text-[#4e4a46] transition-colors hover:border-[#B4232C] hover:text-[#B4232C]">Track a Repair</Link>
            </div>
          </div>
          <div className="relative mx-auto w-full max-w-[530px] lg:mx-0 lg:justify-self-end">
            <div className="absolute -right-4 -top-5 h-24 w-24 rounded-3xl border border-[#e9c5c3] bg-[#fff8f6] sm:right-8" />
            <div className="relative rounded-[2rem] border-[10px] border-white bg-[#252525] p-5 shadow-[0_25px_70px_rgba(37,37,37,0.17)] sm:p-7">
              <div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#F06B70]">Your repair journey</p><p className="mt-2 font-display text-2xl font-bold text-white">Clear at every point.</p></div><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#B4232C] text-white"><Check size={21} /></span></div>
              <div className="space-y-4 pt-6">{["Request received", "Diagnosis underway", "Your decision", "Repair completed"].map((item, index) => <div key={item} className="flex items-center gap-3"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${index === 1 ? "bg-[#F06B70] text-[#252525]" : "bg-white/10 text-white/60"}`}>{index + 1}</span><span className={`text-sm ${index === 1 ? "font-bold text-white" : "text-white/55"}`}>{item}</span>{index === 1 && <span className="ml-auto rounded-full bg-white/10 px-2.5 py-1 text-[0.65rem] font-bold uppercase tracking-[0.12em] text-[#F06B70]">Current step</span>}</div>)}</div>
            </div>
            <div className="absolute -bottom-6 -left-3 flex items-center gap-3 rounded-2xl border border-[#e7e2dc] bg-white p-4 shadow-[0_18px_35px_rgba(37,37,37,0.1)] sm:left-8"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#fff0ef] text-[#B4232C]"><Wrench size={18} /></span><div><p className="text-[0.65rem] font-bold uppercase tracking-[0.15em] text-[#9a9690]">Repair support</p><p className="mt-0.5 text-sm font-bold text-[#252525]">One step at a time</p></div></div>
          </div>
        </div>
      </section>

      <section className="bg-white px-5 py-24 sm:px-8 lg:px-10 lg:py-32">
        <div className="mx-auto max-w-7xl"><div className="max-w-2xl"><SectionEyebrow>What FixPoint helps with</SectionEyebrow><h2 className="font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">Good repair starts with <span className="text-[#B4232C]">good information.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-[#77736e]">The customer experience is designed to make the important moments easy to understand, from describing an issue to deciding what happens next.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{customerBenefits.map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-[1.5rem] border border-[#e9e6e1] bg-[#fbfaf8] p-6 sm:p-7"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff0ef] text-[#B4232C]"><Icon size={22} /></span><span className="font-display text-2xl font-bold text-[#d9d4cd]">0{index + 1}</span></div><h3 className="mt-8 font-display text-xl font-bold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#817c76]">{text}</p></article>)}</div></div>
      </section>

      <section className="bg-[#252525] px-5 py-24 text-white sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><SectionEyebrow light>How it works</SectionEyebrow><h2 className="font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">A repair process you can <span className="text-[#F06B70]">follow.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-white/55">Each request moves through a simple sequence so customers know where things stand and what decision comes next.</p></div><div className="mt-16 grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{processSteps.map((step) => <article key={step.number} className="relative border-t border-white/15 pt-5"><span className="font-display text-3xl font-bold text-[#F06B70]">{step.number}</span><h3 className="mt-5 max-w-xs font-display text-xl font-bold leading-tight">{step.title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-white/50">{step.text}</p></article>)}</div></div></section>

      <section className="bg-[#f5f4f1] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><SectionEyebrow>Repair tracking</SectionEyebrow><h2 className="font-display text-4xl font-bold leading-[1.02] tracking-[-0.06em] sm:text-5xl">Know what is happening with your <span className="text-[#B4232C]">repair.</span></h2><p className="mt-7 max-w-xl text-base leading-7 text-[#6f6a64]">The tracking page gives you a place to check the latest status of a repair using its reference details. It is designed for quick updates when you want them, without needing to retrace the whole conversation.</p><Link to="/track" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#252525] px-6 py-4 text-sm font-bold text-white transition-transform hover:-translate-y-1">Track a Repair <ArrowRight size={17} /></Link></div><div className="rounded-[2rem] border border-[#e4dfd8] bg-white p-6 shadow-[0_18px_40px_rgba(37,37,37,0.06)] sm:p-8"><div className="flex items-center gap-3 border-b border-[#eeeae5] pb-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#fff0ef] text-[#B4232C]"><Eye size={21} /></span><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#9a9690]">Customer view</p><p className="mt-1 font-display text-xl font-bold">A simple status check</p></div></div><div className="space-y-5 pt-6"><div><div className="flex items-center justify-between text-sm font-bold"><span>Repair status</span><span className="text-[#B4232C]">Latest update</span></div><div className="mt-3 h-2 rounded-full bg-[#eeeae5]"><div className="h-2 w-2/3 rounded-full bg-[#B4232C]" /></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#fbfaf8] p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a9690]">Reference</p><p className="mt-2 text-sm font-bold text-[#4e4a46]">Your repair details</p></div><div className="rounded-xl bg-[#fbfaf8] p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a9690]">Next step</p><p className="mt-2 text-sm font-bold text-[#4e4a46]">See what comes next</p></div></div></div></div></div></section>

      <section className="bg-white px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><div><SectionEyebrow>Behind the repair</SectionEyebrow><h2 className="font-display text-4xl font-bold leading-[1.02] tracking-[-0.06em] sm:text-5xl">A coordinated workflow, kept <span className="text-[#B4232C]">customer-friendly.</span></h2><p className="mt-7 max-w-lg text-base leading-7 text-[#6f6a64]">Technicians and staff work from the same repair request so diagnosis, quotations, updates, and completion stay connected. Customers see the useful progress and decisions without being exposed to internal tools or private operational details.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[1.5rem] border border-[#e9e6e1] bg-[#fbfaf8] p-6 sm:p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff0ef] text-[#B4232C]"><Wrench size={22} /></span><h3 className="mt-7 font-display text-xl font-bold">Technician workflow</h3><p className="mt-3 text-sm leading-6 text-[#817c76]">Technicians review the request, diagnose the device, record the work needed, and keep the repair moving through the agreed process.</p></article><article className="rounded-[1.5rem] border border-[#e9e6e1] bg-[#fbfaf8] p-6 sm:p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff0ef] text-[#B4232C]"><FileText size={22} /></span><h3 className="mt-7 font-display text-xl font-bold">Staff workflow</h3><p className="mt-3 text-sm leading-6 text-[#817c76]">Staff coordinate requests, quotations, customer communication, assignments, and completion so each repair has a clear next step.</p></article></div></div></section>

      <section className="bg-[#f5f4f1] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionEyebrow>Service catalog</SectionEyebrow><h2 className="font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">Support for the devices you <span className="text-[#B4232C]">depend on.</span></h2></div><p className="max-w-sm text-sm leading-6 text-[#77736e]">Choose the category that best matches what you need. The repair request form uses the same catalog categories.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{serviceCategories.map((category, index) => { const Icon = categoryIcons[index] ?? Wrench; return <div key={category} className="flex items-center gap-4 rounded-2xl border border-[#e4dfd8] bg-white p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#fff0ef] text-[#B4232C]"><Icon size={18} /></span><span className="text-sm font-bold text-[#4e4a46]">{category}</span></div>; })}</div><Link to="/request" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#B4232C] px-6 py-4 text-sm font-bold text-white shadow-[0_14px_28px_rgba(180,35,44,0.18)] transition-transform hover:-translate-y-1">Request a Repair <ArrowRight size={17} /></Link></div></section>

      <section className="px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-[#B4232C] p-8 sm:p-12 lg:flex lg:items-center lg:justify-between lg:gap-12 lg:p-16"><div><SectionEyebrow light>Ready when you are</SectionEyebrow><h2 className="max-w-2xl font-display text-4xl font-bold tracking-[-0.06em] text-white sm:text-5xl">Start with the next step that makes sense.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/70">Send a repair request if you need help, or check a repair that is already underway.</p></div><div className="mt-8 flex shrink-0 flex-wrap gap-3 lg:mt-0"><Link to="/request" className="inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-sm font-bold text-[#8f1f27] transition-transform hover:-translate-y-1">Request a Repair <ArrowRight size={17} /></Link><Link to="/track" className="inline-flex items-center gap-3 rounded-full border border-white/40 px-6 py-4 text-sm font-bold text-white transition-colors hover:bg-white/10">Track a Repair</Link></div></div></section>

      <footer className="bg-[#252525] px-5 py-10 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 sm:flex-row sm:items-center"><div><Link to="/" aria-label="FixPoint home"><BrandMark inverse /></Link><p className="mt-4 text-xs text-white/40">PC & Laptop Repair Services</p></div><div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-white/50"><Link to="/#services" className="hover:text-white">Services</Link><Link to="/about" className="hover:text-white">About</Link><Link to="/#contact" className="hover:text-white">Contact</Link><Link to="/login" className="font-bold text-[#F06B70]">Staff Login ↗</Link></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/10 pt-5 text-xs text-white/30">© 2025 FixPoint. A temporary prototype brand.</div></footer>
    </div>
  );
}
