import { ArrowRight, Check, ChevronRight, Clock3, Cpu, Database, HardDrive, Laptop, MessageCircle, Monitor, Network, ScanSearch, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { Link } from "react-router-dom";
import { BrandMark, SectionEyebrow } from "@/components/BrandMark";
import { PublicHeader } from "@/components/PublicHeader";

const services = [
  { title: "Laptop Repair", text: "Hinges, screens, batteries, keyboards, and more.", icon: Laptop },
  { title: "PC Repair", text: "Reliable fixes for desktops, towers, and workstations.", icon: Monitor },
  { title: "Diagnostics", text: "Clear answers when your device is slow or failing.", icon: ScanSearch },
  { title: "Cleaning", text: "A cooler, quieter device built for longer life.", icon: Sparkles },
  { title: "Hardware Upgrades", text: "Add the speed and storage your setup needs.", icon: Cpu },
  { title: "Software Support", text: "Setups, tune-ups, updates, and everyday help.", icon: Network },
  { title: "Data Recovery", text: "A careful first step when important files are at risk.", icon: Database },
  { title: "Custom PC Support", text: "Thoughtful guidance for your next build or upgrade.", icon: HardDrive },
];

const steps = [
  { number: "01", title: "Submit Request", text: "Tell us what is happening with your device and choose a convenient way to connect." },
  { number: "02", title: "We Diagnose", text: "Our technicians take a careful look and explain the issue in plain language." },
  { number: "03", title: "Approve Repair", text: "You get a clear recommendation before any repair work begins." },
  { number: "04", title: "Get Your Device Back", text: "We finish the job, keep you updated, and get you back to work." },
];

function HeroVisual() {
  return <div className="relative mx-auto max-w-[620px] lg:mx-0"><div className="absolute -left-7 top-16 hidden h-20 w-20 rounded-3xl border border-[#e9c5c3] bg-[#fff8f6] lg:block" /><div className="relative overflow-hidden rounded-[2rem] border-[10px] border-white bg-[#d6d1c9] shadow-[0_25px_70px_rgba(37,37,37,0.17)]"><img src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=1200&q=85" alt="Technician working on a laptop at a repair bench" className="aspect-[1.12] w-full object-cover" /><div className="absolute inset-0 bg-[#252525]/10" /><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl border border-white/40 bg-[#252525]/85 p-4 text-white backdrop-blur-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#B4232C]"><ShieldCheck size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-white/55">The FixPoint promise</p><p className="mt-0.5 text-sm font-semibold">Clear work. No surprises.</p></div></div><span className="hidden text-2xl font-light text-white/35 sm:block">↗</span></div></div><div className="absolute -bottom-7 -right-3 flex items-center gap-3 rounded-2xl border border-[#e7e2dc] bg-white p-4 shadow-[0_18px_35px_rgba(37,37,37,0.1)] sm:right-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#fff0ef] text-[#B4232C]"><Clock3 size={19} /></span><div><p className="text-[0.65rem] font-bold uppercase tracking-[0.15em] text-[#9a9690]">Repair updates</p><p className="mt-0.5 text-sm font-bold text-[#252525]">At every step</p></div></div></div>;
}

export default function Index() {
  return <div id="top" className="overflow-hidden bg-[#fbfaf8] text-[#252525]">
    <section className="relative min-h-[720px] bg-[#f5f4f1]"><PublicHeader /><div className="mx-auto grid max-w-7xl items-center gap-16 px-5 pb-28 pt-36 sm:px-8 lg:grid-cols-[0.92fr_1.08fr] lg:px-10 lg:pb-32 lg:pt-44"><div className="animate-fade-up"><SectionEyebrow>Local care. Expert repair.</SectionEyebrow><h1 className="max-w-xl font-display text-[3.6rem] font-bold leading-[0.96] tracking-[-0.07em] sm:text-6xl lg:text-[5.3rem]">Reliable repair, <span className="text-[#B4232C]">made simple.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#66615b] sm:text-lg">From the first diagnosis to the final handoff, FixPoint makes getting your computer back on track feel straightforward.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link to="/request" className="group inline-flex items-center gap-3 rounded-full bg-[#B4232C] px-6 py-4 text-sm font-bold text-white shadow-[0_14px_28px_rgba(180,35,44,0.2)] transition-transform hover:-translate-y-1">Request a Repair <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></Link><Link to="/track" className="inline-flex items-center gap-2 rounded-full border border-[#d9d5cf] bg-white px-6 py-4 text-sm font-bold text-[#4e4a46] transition-colors hover:border-[#B4232C] hover:text-[#B4232C]">Track My Repair</Link></div><div className="mt-10 flex items-center gap-5 text-xs font-semibold text-[#8a857e]"><span className="flex items-center gap-2"><Check size={15} className="text-[#B4232C]" />Clear recommendations</span><span className="hidden h-4 w-px bg-[#d4d0ca] sm:block" /><span className="hidden items-center gap-2 sm:flex"><Check size={15} className="text-[#B4232C]" />Local, human support</span></div></div><HeroVisual /></div><div className="absolute bottom-0 left-1/2 hidden -translate-x-1/2 translate-y-1/2 items-center gap-6 rounded-full border border-[#e4e0da] bg-white px-6 py-4 text-xs font-bold uppercase tracking-[0.13em] text-[#77736e] shadow-sm lg:flex"><span>PC & Laptop Repair Services</span><span className="h-1.5 w-1.5 rounded-full bg-[#B4232C]" /><span>Built around your peace of mind</span></div></section>
    <section id="services" className="scroll-mt-10 bg-white px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionEyebrow>What we do</SectionEyebrow><h2 className="max-w-xl font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">Good service starts with <span className="text-[#B4232C]">good listening.</span></h2></div><p className="max-w-sm text-sm leading-6 text-[#77736e]">Practical support for the devices you rely on every day, with recommendations that make sense for you.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map(({ title, text, icon: Icon }, index) => <div key={title} className="group rounded-[1.35rem] border border-[#e9e6e1] bg-[#fbfaf8] p-5 transition-all hover:-translate-y-1 hover:border-[#e7b3b1] hover:bg-[#fff8f7]"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-[#B4232C] shadow-sm"><Icon size={21} strokeWidth={1.8} /></span><span className="text-xs font-bold text-[#c9c5bf]">0{index + 1}</span></div><h3 className="mt-7 font-display text-lg font-bold tracking-[-0.03em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#817c76]">{text}</p><div className="mt-5 flex items-center gap-1 text-xs font-bold text-[#B4232C] opacity-0 transition-opacity group-hover:opacity-100">Learn more <ChevronRight size={14} /></div></div>)}</div></div></section>
    <section id="how-it-works" className="scroll-mt-10 bg-[#252525] px-5 py-24 text-white sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><SectionEyebrow light>How it works</SectionEyebrow><h2 className="font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">Less guessing.<br /><span className="text-[#F06B70]">More getting it fixed.</span></h2></div><div className="mt-16 grid gap-10 md:grid-cols-4 md:gap-5">{steps.map((step, index) => <div key={step.number} className="relative"><div className="mb-6 flex items-center justify-between"><span className="font-display text-3xl font-bold text-[#F06B70]">{step.number}</span>{index < 3 && <span className="hidden h-px w-2/3 bg-white/15 md:block" />}</div><h3 className="font-display text-xl font-bold">{step.title}</h3><p className="mt-3 max-w-[230px] text-sm leading-6 text-white/50">{step.text}</p></div>)}</div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] bg-[#B4232C] lg:grid-cols-[1.1fr_0.9fr]"><div className="p-8 sm:p-12 lg:p-16"><SectionEyebrow light>Stay in the loop</SectionEyebrow><h2 className="max-w-lg font-display text-4xl font-bold tracking-[-0.06em] text-white sm:text-5xl">Wondering where your repair stands?</h2><p className="mt-5 max-w-md text-base leading-7 text-white/70">Use your repair reference to see the latest update whenever it suits you. No phone tag required.</p><Link to="/track" className="mt-8 inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-sm font-bold text-[#8f1f27] transition-transform hover:-translate-y-1">Track My Repair <ArrowRight size={17} /></Link></div><div className="relative hidden min-h-[300px] bg-[#9e2028] lg:block"><div className="absolute left-16 top-16 h-48 w-72 rotate-[-7deg] rounded-2xl border-8 border-white/80 bg-[#f8f5f1] p-5 shadow-xl"><div className="h-3 w-20 rounded-full bg-[#252525]/15" /><div className="mt-6 flex gap-2"><span className="h-20 w-1 rounded-full bg-[#B4232C]" /><span className="flex-1 rounded-lg bg-[#e8e3dc]" /></div><div className="mt-4 h-2 w-28 rounded-full bg-[#252525]/10" /></div><div className="absolute bottom-14 right-16 flex h-16 w-16 items-center justify-center rounded-full bg-white text-[#B4232C] shadow-lg"><Check size={28} /></div></div></div></section>
    <section id="about" className="scroll-mt-10 bg-[#f5f4f1] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[0.9fr_1.1fr]"><div className="relative"><div className="overflow-hidden rounded-[2rem] bg-[#d9d4cc] shadow-[0_20px_45px_rgba(37,37,37,0.12)]"><img src="https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=85" alt="Friendly technician in a local computer repair workshop" className="aspect-[0.9] w-full object-cover" /></div><div className="absolute -bottom-5 -right-4 rounded-2xl bg-white p-4 shadow-lg sm:right-7"><div className="flex items-center gap-3"><MessageCircle size={20} className="text-[#B4232C]" /><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a9690]">The FixPoint way</p><p className="mt-1 text-sm font-bold">Friendly & straight-talking</p></div></div></div></div><div><SectionEyebrow>Why FixPoint</SectionEyebrow><h2 className="font-display text-4xl font-bold leading-[1.02] tracking-[-0.06em] sm:text-5xl">The kind of repair service you can <span className="text-[#B4232C]">feel good about.</span></h2><p className="mt-7 max-w-xl text-base leading-7 text-[#6f6a64]">We believe computer repair should feel less like a mystery and more like a conversation. FixPoint is a professional local service built around careful work, clear communication, and respect for your time.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="flex gap-3"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-[#B4232C]" /><div><p className="font-bold">Transparent by default</p><p className="mt-1 text-sm leading-5 text-[#817c76]">You stay in the loop before decisions are made.</p></div></div><div className="flex gap-3"><Wrench size={20} className="mt-0.5 shrink-0 text-[#B4232C]" /><div><p className="font-bold">Careful hands-on work</p><p className="mt-1 text-sm leading-5 text-[#817c76]">Thoughtful troubleshooting, not guesswork.</p></div></div></div></div></div></section>
    <section id="contact" className="scroll-mt-10 bg-white px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><SectionEyebrow>Come say hello</SectionEyebrow><h2 className="font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">Have a question?<br /><span className="text-[#B4232C]">We are here.</span></h2><p className="mt-6 max-w-sm text-sm leading-6 text-[#77736e]">Reach out for a quick conversation about your device, or stop by our workshop when it is convenient.</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#e9e6e1] p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9a9690]">Call us</p><p className="mt-3 font-bold">(000) 000-0000</p><p className="mt-1 text-sm text-[#817c76]">Mon–Fri, 9am–5pm</p></div><div className="rounded-2xl border border-[#e9e6e1] p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9a9690]">Visit us</p><p className="mt-3 font-bold">123 Repair Street</p><p className="mt-1 text-sm text-[#817c76]">Your town, ST 00000</p></div><div className="rounded-2xl border border-[#e9e6e1] p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9a9690]">Email</p><p className="mt-3 break-all font-bold">hello@fixpoint.local</p><p className="mt-1 text-sm text-[#817c76]">We reply within a day</p></div></div></div></div></section>
    <footer className="bg-[#252525] px-5 py-10 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 sm:flex-row sm:items-center"><div><Link to="/" aria-label="FixPoint home"><BrandMark inverse /></Link><p className="mt-4 text-xs text-white/40">PC & Laptop Repair Services</p></div><div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-white/50"><a href="/#services" className="hover:text-white">Services</a><a href="/#about" className="hover:text-white">About</a><a href="/#contact" className="hover:text-white">Contact</a><Link to="/login" className="font-bold text-[#F06B70]">Staff Login ↗</Link></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/10 pt-5 text-xs text-white/30">© 2025 FixPoint. A temporary prototype brand.</div></footer>
  </div>;
}
