import { useCallback, useEffect, useState } from "react";
import { FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { formatQuotationDate, formatQuotationDateTime, listQuotations, type QuotationStatus, type ServiceRequestQuotation } from "@/lib/quotations";

const peso = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
const money = (value: number) => peso.format(Number(value) || 0);
const statusStyles: Record<QuotationStatus, string> = { draft: "bg-[#f2f0ec] text-[#5f5b57]", sent: "bg-[#fff0ef] text-[#8f1f27]", approved: "bg-[#edf8f0] text-[#267342]", declined: "bg-[#fff7e8] text-[#946516]", expired: "bg-[#f2f0ec] text-[#77736e]", cancelled: "bg-[#f2f0ec] text-[#77736e]" };

function StatusBadge({ status }: { status: QuotationStatus }) {
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusStyles[status]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

function QuotationDetails({ quotation }: { quotation: ServiceRequestQuotation }) {
  return <div className="mt-5 space-y-4 border-t border-[#eeeae5] pt-5"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Total Amount</p><p className="mt-1 font-display text-xl font-bold text-[#B4232C]">{money(quotation.total_amount)}</p></div><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Valid Until</p><p className="mt-1 text-sm font-semibold text-[#4e4a46]">{formatQuotationDate(quotation.valid_until)}</p></div><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Response Date</p><p className="mt-1 text-sm font-semibold text-[#4e4a46]">{formatQuotationDateTime(quotation.responded_at)}</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Diagnosis Summary</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[#4e4a46]">{quotation.diagnosis_summary || "Not provided"}</p></div><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Customer Message</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[#4e4a46]">{quotation.customer_message || "Not provided"}</p></div></div><div><p className="text-[0.68rem] font-bold uppercase tracking-[0.1em] text-[#9a9690]">Quotation Items</p><div className="mt-2 space-y-2">{quotation.items.map((item) => <div key={item.id ?? `${item.item_type}-${item.description}`} className="flex items-start justify-between gap-4 rounded-xl bg-[#fbfaf8] px-3 py-2.5"><div><p className="text-sm font-bold text-[#4e4a46]">{item.description}</p><p className="mt-0.5 text-xs capitalize text-[#817c76]">{item.item_type} · {item.quantity} × {money(item.unit_price)}</p></div><span className="text-sm font-bold text-[#3e3a36]">{money(item.line_total)}</span></div>)}</div></div>{quotation.response && <div className="rounded-xl border border-[#ead9d6] bg-[#fffaf9] p-3"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#8f1f27]">Customer response: <span className="capitalize">{quotation.response}</span></p>{quotation.customer_name && <p className="mt-2 text-sm font-semibold text-[#4e4a46]">{quotation.customer_name}{quotation.customer_phone ? ` · ${quotation.customer_phone}` : ""}</p>}{quotation.customer_comment && <p className="mt-1 text-sm leading-6 text-[#5f5b57]">{quotation.customer_comment}</p>}</div>}</div>;
}

export function QuotationHistory({ requestId }: { requestId: string }) {
  const [quotations, setQuotations] = useState<ServiceRequestQuotation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const load = useCallback(async () => { setIsLoading(true); try { setQuotations(await listQuotations(requestId)); } catch (error) { toast.error(error instanceof Error ? error.message : "Customer quotations could not be loaded."); } finally { setIsLoading(false); } }, [requestId]);
  useEffect(() => { void load(); }, [load]);
  return <section className="rounded-[1.5rem] border border-[#ead9d6] bg-white p-5 shadow-[0_12px_35px_rgba(180,35,44,0.04)] sm:p-7"><div className="flex items-center gap-3 border-b border-[#eeeae5] pb-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0ef] text-[#B4232C]"><FileText size={18} /></span><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#B4232C]">Customer Quotations</p><h2 className="mt-1 font-display text-xl font-bold tracking-[-0.04em]">Quotation history</h2></div></div>{isLoading ? <div className="py-8 text-center text-sm text-[#817c76]"><Loader2 className="mx-auto mb-2 animate-spin text-[#B4232C]" size={21} />Loading quotations...</div> : quotations.length === 0 ? <p className="pt-5 text-sm text-[#817c76]">No customer quotations have been prepared for this request.</p> : <div className="space-y-4 pt-5">{quotations.map((quotation) => <article key={quotation.id} className="rounded-2xl border border-[#e5e1db] bg-[#fffefd] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-lg font-bold text-[#2f2c29]">{quotation.quotation_number}</p><p className="mt-1 text-xs text-[#817c76]">Created {formatQuotationDateTime(quotation.created_at)} · Sent {formatQuotationDateTime(quotation.sent_at)}</p></div><StatusBadge status={quotation.status} /></div><QuotationDetails quotation={quotation} /></article>)}</div>}</section>;
}

export default QuotationHistory;
